name: Frontend Deploy

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Create .env.staging
        run: | 
          echo "VITE_API_BASE_URL=${{ secrets.J_VITE_API_BASE_URL_STAGING }}" > .env.staging
          echo "VITE_APP_BASE_URL=${{ secrets.J_VITE_APP_BASE_URL_STAGING }}" >> .env.staging
          echo "VITE_KAKAO_REST_API_KEY=${{ secrets.R_VITE_KAKAO_REST_API_KEY_STAGING }}" >> .env.staging
          echo "VITE_KAKAO_REDIRECT_URI=${{ secrets.J_VITE_KAKAO_REDIRECT_URI_STAGING }}" >> .env.staging
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env.staging

          
      - name: Build
        run: npm run build -- --mode staging 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.J_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.J_AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.J_AWS_REGION }}

      - run: ls -lh dist && echo "BUCKET=${{ secrets.J_S3_BUCKET_NAME }}"
      - run: aws s3 ls "s3://${{ secrets.J_S3_BUCKET_NAME }}/" --human-readable --summarize
      - run: aws s3 sync dist/ "s3://${{ secrets.J_S3_BUCKET_NAME }}" --delete --exact-timestamps --no-progress


      - name: Upload to S3
      #   run: |
      #     aws s3 sync dist/ s3://${{ secrets.J_S3_BUCKET_NAME }} --delete
        run: |
            BUCKET="${{ secrets.J_S3_BUCKET_NAME }}"
  
            aws s3 sync dist/ "s3://$BUCKET" \
              --delete --exact-timestamps --no-progress \
              --exclude "*" --include "*.js" \
              --content-type "application/javascript" \
              --metadata-directive REPLACE
  
            aws s3 sync dist/ "s3://$BUCKET" \
              --exclude "*" --include "*.css" \
              --content-type "text/css" \
              --metadata-directive REPLACE
  
            aws s3 sync dist/ "s3://$BUCKET" \
              --delete --exact-timestamps --no-progress \
              --exclude "*.js" --exclude "*.css"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.J_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
